
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace P2_Q1
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
                This part is to check whether a given string can be accepted by the grammar or not.
                1. Is grammar in Chomsky Normal Form? If no convert it.
                2. Use CYK algorithm to check if the string can be generated by the grammar.
            */
            int n = Convert.ToInt32(Console.ReadLine());
            List<List<string>> grammar = new List<List<string>>();

            List<string> tmp = new List<string>();
            List<string> RHS = new List<string>();

            for (int i = 0; i < n; i++)
            {
                tmp = Console.ReadLine().Split(" -> ").ToList();

                RHS = tmp[1].Split("|").ToList();

                List<string> tmp_1 = new List<string>();
                tmp_1.Add(tmp[0]);

                foreach (var item in RHS)
                {
                    tmp_1.Add(item.Trim());
                }

                grammar.Add(tmp_1);
            }

            Grammar inputGrammar = new Grammar(grammar);

            string? inputString = Console.ReadLine();

            string result = inputGrammar.isAcceptedByGrammar(inputString);

            System.Console.WriteLine(result);
        }
    }
}
